[package]
name = "burn-rl-examples"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
rand = "0.8.4"
burn = "0.8.0"
burn-autodiff = "0.8.0"
burn-ndarray = "0.8.0"
ndarray = "0.15.6"
ndarray-linalg = "0.16.0"
nannou = "0.18.1"
