[package]
name = "burn-rl-examples"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
burn = { version = "0.11.1", features = ["ndarray", "autodiff"] }
burn-autodiff = "0.11.1"
serde = { workspace = true }

burn-rl = { path = "../burn-rl" }

[features]
default = ["burn/ndarray"]
